export interface Movie {
  id: string;
  title: string;
  year: string;
  duration: string;
  rating: string;
  genres?: string[];
  description?: string;
  director?: string;
  cast?: string[];
  imageUrl: string;
  releaseDate?: string;
  language?: string;
  videoUrl: string;
}

export const movies: Movie[] = [
  {
    id: "1",
    title: "Kabaddi 4: The Final Match",
    year: "2022",
    duration: "2h 15m",
    rating: "4.7",
    genres: ["Comedy", "Drama", "Sport"],
    description:
      "The final installment in the beloved Kabaddi series brings our heroes back for one last epic match that will determine the future of their village.",
    director: "Ram Babu Gurung",
    cast: ["Dayahang Rai", "Saugat Malla", "Miruna Magar", "Karma Shakya"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/8/82/Kabaddi_4_poster.jpg/250px-Kabaddi_4_poster.jpg",
    releaseDate: "September 15, 2022",
    language: "Nepali",
    videoUrl: "https://www.youtube.com/watch?v=7WR3qzB40V8",
  },
  {
    id: "2",
    title: "Chiso Maanche",
    year: "2023",
    duration: "2h 15m",
    rating: "4.3",
    genres: ["Drama"],
    description:
      "A poignant Nepali drama exploring human struggles and resilience in a changing world.",
    director: "Arpan Thapa",
    cast: ["Arpan Thapa", "Swastima Khadka", "Desh Bhakta Khanal"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/0/02/Chiso_Manchhe.jpg",
    releaseDate: "January 1, 2023",
    language: "Nepali",
    videoUrl: "https://www.youtube.com/watch?v=VIDEO_ID_2",
  },
  {
    id: "3",
    title: "Pashupati Prasad",
    year: "2016",
    duration: "2h 20m",
    rating: "4.8",
    genres: ["Drama"],
    description:
      "A touching story of a young man’s journey through loss and redemption in Kathmandu.",
    director: "Dipendra K Khanal",
    cast: ["Khagendra Lamichhane", "Rabindra Singh Baniya"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/a/a7/Pashupati_Prasad_poster.jpg",
    releaseDate: "January 1, 2016",
    language: "Nepali",
    videoUrl: "https://www.youtube.com/watch?v=xGOIMWh2FfE",
  },
  {
    id: "4",
    title: "Chhakka Panja 4",
    year: "2023",
    duration: "2h 10m",
    rating: "4.2",
    genres: ["Comedy", "Family"],
    description:
      "The latest in the popular Chhakka Panja series, filled with humor and social commentary.",
    director: "Deepa Shree Niraula",
    cast: ["Deepak Raj Giri", "Deepa Shree Niraula", "Kedar Ghimire"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/1/1e/Chhakka_Panja_4.jpg",
    releaseDate: "March 1, 2023",
    language: "Nepali",
    videoUrl: "https://www.youtube.com/watch?v=06LGYNAB5lY",
  },
  {
    id: "5",
    title: "Talakjung vs Tulke",
    year: "2014",
    duration: "2h 15m",
    rating: "4.6",
    genres: ["Drama"],
    description:
      "A story of rivalry and redemption set against the backdrop of Nepal’s civil war.",
    director: "Nischal Basnet",
    cast: ["Khum Narayan Bhusal", "Dayahang Rai"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/1/13/Talakjung_vs_Tulke_movie_poster.jpg",
    releaseDate: "January 1, 2014",
    language: "Nepali",
    videoUrl: "https://www.youtube.com/watch?v=Zl-JXV0JTzw",
  },
  {
    id: "6",
    title: "Bulbul",
    year: "2019",
    duration: "2h 10m",
    rating: "4.4",
    genres: ["Drama"],
    description:
      "A heartfelt tale of a tempo driver navigating life’s challenges in Kathmandu.",
    director: "Binod Paudel",
    cast: ["Swastima Khadka", "Mukund Bahadur Thapa"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/f/f3/Bulbul_-_film_poster.jpg",
    releaseDate: "January 1, 2019",
    language: "Nepali",
    videoUrl: "https://www.youtube.com/watch?v=VIDEO_ID_6",
  },
  {
    id: "7",
    title: "Sano Mann",
    year: "2018",
    duration: "2h 5m",
    rating: "4.3",
    genres: ["Romance", "Drama"],
    description:
      "A romantic drama exploring love and relationships in modern Nepal.",
    director: "Sujeet Bidari",
    cast: ["Shristi Shrestha", "Ayushman Deshraj"],
    imageUrl: "https://www.thefilmnepal.com/uploads/medias/sanomann.jpg",
    releaseDate: "January 1, 2018",
    language: "Nepali",
    videoUrl: "https://www.youtube.com/watch?v=442Aw7Dj_2w",
  },
  {
    id: "8",
    title: "Saili",
    year: "2023",
    duration: "2h 10m",
    rating: "4.1",
    genres: ["Drama"],
    description:
      "A story of love and sacrifice in rural Nepal.",
    director: "Ram Babu Gurung",
    cast: ["Dayahang Rai", "Menuka Pradhan"],
    imageUrl: "https://m.media-amazon.com/images/M/MV5BNDg0NmVmYjEtYzU4MC00M2QwLWIzNzAtZWM3ZjJlMGQzZTBjXkEyXkFqcGc@._V1_.jpg",
    releaseDate: "January 1, 2023",
    language: "Nepali",
    videoUrl: "https://www.youtube.com/watch?v=p8_YI_dNImM",
  },
  {
    id: "9",
    title: "Garud Puran",
    year: "2023",
    duration: "2h 15m",
    rating: "4.0",
    genres: ["Drama"],
    description:
      "A modern take on traditional Nepali beliefs and family dynamics.",
    director: "Suman Upreti",
    cast: ["Karma Shakya", "Priyanka Karki"],
    imageUrl: "https://m.media-amazon.com/images/M/MV5BMDdkODM3MDAtZTQ2MS00MDVjLWJkMTItMmUzNTcwNmQ1ZDZlXkEyXkFqcGc@._V1_.jpg",
    releaseDate: "January 1, 2023",
    language: "Nepali",
    videoUrl: "https://www.youtube.com/watch?v=5E-wEcf3t1Y",
  },
  {
    id: "10",
    title: "Cha Maya Chapakkai",
    year: "2023",
    duration: "2h 10m",
    rating: "4.2",
    genres: ["Comedy", "Romance"],
    description:
      "A lighthearted romantic comedy about love and misunderstandings.",
    director: "Dipendra Lama",
    cast: ["Deepak Raj Giri", "Kedar Ghimire"],
    imageUrl: "https://m.media-amazon.com/images/M/MV5BOWI1YTNhZjAtYzhmYS00ZmQ0LTg0NDgtYzEwZWQ3MGRkNTUwXkEyXkFqcGc@._V1_.jpg",
    releaseDate: "January 1, 2023",
    language: "Nepali",
    videoUrl: "https://www.youtube.com/watch?v=JvTaYFnFInY",
  },
  {
    id: "11",
    title: "Lakka Jawan",
    year: "2023",
    duration: "2h 5m",
    rating: "3.9",
    genres: ["Comedy"],
    description:
      "A comedic tale of youthful adventures and mishaps.",
    director: "Seshraj Bhattarai",
    cast: ["Dilip Rayamajhi", "Priyanka Karki"],
    imageUrl: "https://www.thefilmnepal.com/uploads/medias/lakkajawan.jpg",
    releaseDate: "January 1, 2023",
    language: "Nepali",
    videoUrl: "https://www.youtube.com/watch?v=KwMI_u4CSzc",
  },
  {
    id: "12",
    title: "Gorkha Warrior",
    year: "2023",
    duration: "2h 20m",
    rating: "4.5",
    genres: ["Action", "Drama"],
    description:
      "An action-packed story of bravery and sacrifice inspired by Gorkha soldiers.",
    director: "Milan Chams",
    cast: ["Ritesh Chams", "Suryamala Sharma"],
    imageUrl: "https://m.media-amazon.com/images/M/MV5BZmVkMWQ2NGMtYjNiMS00MjcyLWEwZTItZTU2MTk2MzFhMmRjXkEyXkFqcGc@._V1_.jpg",
    releaseDate: "January 1, 2023",
    language: "Nepali",
    videoUrl: "https://www.youtube.com/watch?v=rEog10wE6A0",
  },
  {
    id: "13",
    title: "Loot 2",
    year: "2017",
    duration: "2h 15m",
    rating: "4.5",
    genres: ["Action", "Crime"],
    description:
      "The thrilling sequel to Loot, following the aftermath of a heist.",
    director: "Nischal Basnet",
    cast: ["Saugar Malla", "Dayahang Rai"],
  imageUrl: "https://m.media-amazon.com/images/M/MV5BYjAxOGIxMmQtOGEzYS00NDBiLTkyZGQtMzM4MGQ5YzIzMDk2XkEyXkFqcGc@._V1_.jpg",
  releaseDate: "January 1, 2017",
  language: "Nepali",
  videoUrl: "https://www.youtube.com/watch?v=7uVU6QAvgG8",
},
  {
    id: "14",
    title: "Machha Machha",
    year: "2019",
    duration: "2h 10m",
    rating: "4.0",
    genres: ["Action", "Comedy"],
    description:
      "A fun action-comedy about a group of friends caught in a chaotic adventure.",
    director: "Jeevan Rijal",
    cast: ["Saugat Malla", "Anup Bikram Shahi"],
    imageUrl: "https://www.thefilmnepal.com/uploads/medias/machhamachha.jpg",
    releaseDate: "January 1, 2019",
    language: "Nepali",
    videoUrl: "https://www.youtube.com/watch?v=bV2e2bnu9LQ",
  },
  {
    id: "15",
    title: "Bir Bikram",
    year: "2016",
    duration: "2h 15m",
    rating: "4.2",
    genres: ["Action", "Romance"],
    description:
      "A romantic action drama about friendship and love.",
    director: "Milan Chams",
    cast: ["Dayahang Rai", "Anup Bikram Shahi"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Birbikramposter.jpg/250px-Birbikramposter.jpg",
    releaseDate: "January 1, 2016",
    language: "Nepali",
    videoUrl: "https://www.youtube.com/watch?v=YZ2hdVphpaI",
  },
  {
    id: "16",
    title: "Bir Bikram 2",
    year: "2019",
    duration: "2h 10m",
    rating: "4.3",
    genres: ["Action", "Romance"],
    description:
      "The sequel to Bir Bikram, continuing the saga of love and action.",
    director: "Milan Chams",
    cast: ["Paul Shah", "Barsha Siwakoti"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/7/78/Bir_Bikram_2.jpg",
    releaseDate: "January 1, 2019",
    language: "Nepali",
    videoUrl: "https://www.youtube.com/watch?v=QupWAlzGAHE",
  },
  {
    id: "17",
    title: "Jatra",
    year: "2016",
    duration: "2h 15m",
    rating: "4.4",
    genres: ["Action", "Comedy"],
    description:
      "A comedic heist story filled with twists and turns.",
    director: "Pradeep Bhattarai",
    cast: ["Bipin Karki", "Rabindra Jha"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/8/8f/Jatranepalimovieposter.jpg",
    releaseDate: "January 1, 2016",
    language: "Nepali",
    videoUrl: "https://www.youtube.com/watch?v=SLTQeRlb0dk",
  },
  {
    id: "18",
    title: "Kusume Rumal",
    year: "1985",
    duration: "2h 30m",
    rating: "4.9",
    genres: ["Romance", "Drama"],
    description:
      "A classic Nepali love story that defined a generation.",
    director: "Tulsi Ghimire",
    cast: ["Bhuwan K.C.", "Tripti Nadakar"],
    imageUrl: "https://www.thefilmnepal.com/uploads/medias/kusumerumal.jpg",
    releaseDate: "January 1, 1985",
    language: "Nepali",
    videoUrl: "https://www.youtube.com/watch?v=er7Pb0-ToHo",
  },
  {
    id: "19",
    title: "Balidaan",
    year: "1996",
    duration: "2h 25m",
    rating: "4.8",
    genres: ["Drama"],
    description:
      "A patriotic drama about sacrifice and honor.",
    director: "Tulsi Ghimire",
    cast: ["Hari Bansha Acharya", "Madhu Shahi"],
    imageUrl: "https://www.thefilmnepal.com/uploads/medias/balidaan.jpg",
    releaseDate: "January 1, 1996",
    language: "Nepali",
    videoUrl: "https://www.youtube.com/watch?v=gmZq4wLOaiw",
  },
  {
    id: "20",
    title: "Maitighar",
    year: "1966",
    duration: "2h 20m",
    rating: "4.7",
    genres: ["Drama"],
    description:
      "One of Nepal’s first feature films, a story of family and tradition.",
    director: "B.S. Thapa",
    cast: ["Mala Sinha", "C.P. Lohani"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/0/0a/Maitighar.jpg/250px-Maitighar.jpg",
    releaseDate: "January 1, 1966",
    language: "Nepali",
    videoUrl: "https://www.youtube.com/watch?v=Orf6uL_KMf0",
  },
  {
    id: "21",
    title: "Darpan Chhaya",
    year: "2001",
    duration: "2h 30m",
    rating: "4.9",
    genres: ["Romance", "Drama"],
    description:
      "A timeless love story of loss and reunion.",
    director: "Tulsi Ghimire",
    cast: ["Dilip Rayamajhi", "Niruta Singh"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/b/b3/DarpanChaya.jpg",
    releaseDate: "January 1, 2001",
    language: "Nepali",
    videoUrl: "https://www.youtube.com/watch?v=SQG-vIuCe_4",
  },
  {
    id: "22",
    title: "Caravan",
    year: "2002",
    duration: "2h 20m",
    rating: "4.8",
    genres: ["Drama"],
    description:
      "A story of human trafficking and survival in the Himalayas.",
    director: "Eric Valli",
    cast: ["Thilen Lhondup", "Lhakpa Tsamchoe"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/0/0d/Himalaya_film.jpg",
    releaseDate: "January 1, 2002",
    language: "Nepali",
    videoUrl: "https://www.youtube.com/watch?v=gMrK7oyzjuk",
  },
  {
    id: "23",
    title: "Numafung",
    year: "2001",
    duration: "2h 15m",
    rating: "4.6",
    genres: ["Drama"],
    description:
      "A story of love and cultural conflict in eastern Nepal.",
    director: "Nabin Subba",
    cast: ["Anupama Subba", "Niwash Limbu"],
    imageUrl: "https://www.thefilmnepal.com/uploads/medias/numafung.jpg",
    releaseDate: "January 1, 2001",
    language: "Nepali",
    videoUrl: "https://www.youtube.com/watch?v=5vhLNNoAYSA",
  },
  {
    id: "24",
    title: "Chhakka Panja",
    year: "2016",
    duration: "2h 10m",
    rating: "4.5",
    genres: ["Comedy", "Family"],
    description:
      "A hilarious comedy tackling social issues with a family-friendly tone.",
    director: "Deepa Shree Niraula",
    cast: ["Deepak Raj Giri", "Priyanka Karki"],
    imageUrl: "https://m.media-amazon.com/images/M/MV5BYTY3N2ZhMTQtODE0OC00YTlkLWFiMzMtYjI1OTY2ZjdlZGQwXkEyXkFqcGc@._V1_.jpg",
    releaseDate: "January 1, 2016",
    language: "Nepali",
    videoUrl: "https://www.youtube.com/watch?v=u5NJUF-M6pc&rco=1",
  },
  {
    id: "25",
    title: "Chhakka Panja 2",
    year: "2017",
    duration: "2h 10m",
    rating: "4.4",
    genres: ["Comedy", "Family"],
    description:
      "The sequel to Chhakka Panja, continuing the comedic adventures.",
    director: "Deepa Shree Niraula",
    cast: ["Deepak Raj Giri", "Swastima Khadka"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/0/06/Chhakka_Panja_2_poster.jpeg/250px-Chhakka_Panja_2_poster.jpeg",
    releaseDate: "January 1, 2017",
    language: "Nepali",
    videoUrl: "https://www.youtube.com/watch?v=q1BzJ6na4Nc",
  },
  {
    id: "26",
    title: "Chhakka Panja 3",
    year: "2018",
    duration: "2h 10m",
    rating: "4.3",
    genres: ["Comedy", "Family"],
    description:
      "The third installment of the Chhakka Panja series, packed with laughs.",
    director: "Deepa Shree Niraula",
    cast: ["Deepak Raj Giri", "Deepa Shree Niraula"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/4/4e/Chhakka_panja_three_ver2.jpg",
    releaseDate: "January 1, 2018",
    language: "Nepali",
    videoUrl: "https://www.youtube.com/watch?v=F9fY5tCg2vc",
  },
  {
    id: "27",
    title: "Woda Number 6",
    year: "2018",
    duration: "2h 5m",
    rating: "4.2",
    genres: ["Comedy", "Family"],
    description:
      "A comedic story of friends navigating life’s challenges.",
    director: "Ujwal Ghimire",
    cast: ["Dayahang Rai", "Kedar Ghimire"],
    imageUrl: "https://www.thefilmnepal.com/uploads/medias/wodanumber6.jpg",
    releaseDate: "January 1, 2018",
    language: "Nepali",
    videoUrl: "https://www.youtube.com/watch?v=HkMh43hJ_tc",
  },
  {
    id: "28",
    title: "Shatru Gate",
    year: "2018",
    duration: "2h 10m",
    rating: "4.1",
    genres: ["Comedy", "Family"],
    description:
      "A family-friendly comedy about rivalry and reconciliation.",
    director: "Madan Ghimire",
    cast: ["Hari Bansha Acharya", "Paul Shah"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/e/ec/Shatru_Gate.jpg",
    releaseDate: "January 1, 2018",
    language: "Nepali",
    videoUrl: "https://www.youtube.com/watch?v=zF4THcBXnYs",
  },
];